export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const GET_RESET_PASSWORD_TOKEN = "GET_RESET_PASSWORD_TOKEN";
export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";

export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
